### ISSUE TITLE
Remove "exit 0" code from rake tasks

### ISSUE THREAD

**Issue by Quentinchampenois** [OpenSourcePolitics/decidim-app#266]
#### Description

Some rake tasks returns exit code 0 when done, it may occur inconsistencies on CI since Rspec returns a 0 status code which means valid status code

#### TODO
- [ ] Remove `exit` statements from rake tasks
- [ ] Avoid exit status code in rake task and whole application

**Comment by armandfardeau** [comment]
For further documentation.

A rake task always returns 0 if not exception has been raised. Therefore if you want to exit 0 just return from the rake task.
